### ISSUE TITLE
urle error

### ISSUE THREAD

**Issue by jeffxusichao** [igormq/ctc_tensorflow_example#17]
Hi, I tried to run the default example.py and encountered this error. I also tried to download the data set from the link directly but also failed. Any idea how I can fix this? Thx!
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

**Comment by dieka13** [comment]
both example works fine for me. you should check your internet connection

**Comment by igormq** [comment]
Did you download @jeffxusichao ?

**Comment by igormq** [comment]
+6 months without response. Closing this issue. Feel free to reopen!
