### ISSUE TITLE
lstm + ctc for mnist

### ISSUE THREAD

**Issue by anxingle** [igormq/ctc_tensorflow_example#2]
Hi, igormq.  It is very helpful to see your [Blog](https://igormq.github.io/2016/07/19/ctc-tensorflow-timit/) talk about CTC on Tensorflow . Thank you a million. But I have some confusion about the CTC module. 
      1.  If sequence is  A B B  * B * B( * is blank).   tf.ctc.ctc_greedy_decoder() should return ABBB.  But [Doc.](https://www.tensorflow.org/versions/r0.10/api_docs/python/nn.html#ctc_loss) say result is A B if merge_repeated =True. 
      2 .  My code is using  [LSTM](https://github.com/anxingle/ctc_example) to classify Mnist data . Just one layer and 28 timeSteps . But [CTC_LOSS](https://github.com/anxingle/ctc_example/blob/master/lstm_mnist.ipynb) don't work at all. Can you help me define the right call style? The code is so simple and I promise U can get it when you see the code .
       Thanks again.

**Comment by anxingle** [comment]
I write just as your code tell me.And  it works well   if comment the CTC functions.   I really don't know what's wrong with it .

**Comment by igormq** [comment]
Thank you @anxingle , I'm very glad that you liked my post. Answering your questions:

1. Yes, you are absolute right, this is the default behavior of TensorFlow's implementation, but in Graves' thesis, he said that you have to delete repeated labels and therefore removing the blank labels, as we can see at page 57 of his thesis. I haven't any clue why the Tensorflow team implemented in that way.
2. I read your code, but it's better if you send to me your error log and your code with the CTC implementation, because in your code I didn't see the `seq_len` placeholder and the sparse placeholder for `y`.  Could you do that?

**Comment by anxingle** [comment]
Thank you very much. I will do what you told me as soon as I can.

**Comment by anxingle** [comment]
I add the entire [code](https://github.com/anxingle/lstm_learn/blob/master/lstm_ctc_mnist.py#L75), and  show me [error.txt](https://github.com/anxingle/lstm_learn/blob/master/error.txt).

**Comment by anxingle** [comment]
I tried tf.int64.

**Comment by igormq** [comment]
Could you send me your dataset?

**Comment by anxingle** [comment]
I have push the mnist dataset into the [data](https://github.com/anxingle/lstm_learn/tree/master/data) ,  you can just git clone the [repository](https://github.com/anxingle/lstm_learn).  
I am really grateful to you.

**Comment by anxingle** [comment]
It takes almost 1 hours.Thanks [GFW](https://en.wikipedia.org/wiki/GFW)

**Comment by igormq** [comment]
Why are you trying to use CTC as a cost function? CTC is used when you don't have an alignment between your input and output and/or the output length vary along the samples. So, for one to one relationship (like one image one digit), CTC probably isn't the best solution for you. But, if you intend to use this code in a continuous hand writing recognition, CTC will work. I'm looking your code and making some changes. As soon as possible I'll give you a feedback, ok?

**Comment by anxingle** [comment]
Thank you for your reply.   But  in this code, I have 28 inputs, so it's a problem  about  many inputs( maybe laterly  I'll add  multi labels) maps to one label.   My senior implement multi labels recognise [ framework mxnet warpctc](https://github.com/dmlc/mxnet/tree/master/example/warpctc) and he told me  it should be the best solution  .       
So nice !

**Comment by igormq** [comment]
Yes, but CTC works only for more than one label.

**Comment by anxingle** [comment]
Got it!  I change another dataset !

**Comment by igormq** [comment]
I made a working code and I put it on [gist](https://gist.github.com/igormq/eff5b2196a52e89c61ea52515ed87c47). You major issue was using the sparse place holder and the sequence length place holder. The targets required by CTC must not be encoded, you must provide as labels and you must feed the sparse place holder as a tuple of `(indices, values, shape)` (that is generated by sparse_tuple_from); in the case for mnist, for batch you will have a target like 

```python
(
[[0, 0], [1, 0], [2, 0], ..., [batch_size-1, 0]],
[label_1, label_2, label_3, ..., label_batch_size],
[batch_size, 1]
)
```

And the `seq_len`placeholder works to tell the rnn what the size of each data in batch, but for MNIST, the network was feed with 28 inputs of length 28, so:

```python
seq_len = [28 for _ in xrange(batch_size)]
```

I hope I could help you. If you have any question I'll be happy to answer you.

**Comment by igormq** [comment]
You can use [this](http://ufldl.stanford.edu/housenumbers/) dataset, whose images have more than one digit and the number of digits differ from image to image. CTC may work better with this dataset.

**Comment by anxingle** [comment]
I even don't know how to express my appreciation ! Thanks  a lot.

**Comment by igormq** [comment]
You're welcome. If you have any questions, please feel free to ask.
