### ISSUE TITLE
multi layer LSTM gives error

### ISSUE THREAD

**Issue by takingstock** [igormq/ctc_tensorflow_example#21]
Hi Igor .. thanks so much for the example but the multi layer LSTM layer gives an error about input sizes mismatching during MATMUL ..its got a solution here ..https://github.com/tensorflow/tensorflow/issues/14897

..kindly update your code

**Comment by igormq** [comment]
Hi @takingstock , when I created this example tensorflow version was < 1.0. This error is due to change of MultiRNNCell API. Feel free to send me a PR :)
